"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-28 02:33:03.979256
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('iiko_sync_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iiko_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iiko_sync_jobs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iiko_sync_jobs_status'), ['status'], unique=False)

    op.create_table('outlets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('iiko_store_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('perceptual_hash', sa.String(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_status', sa.String(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('iiko_product_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_tokens_token'), ['token'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_request_id', sa.String(), nullable=True),
    sa.Column('external_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)

    op.create_table('waste_norms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=True),
    sa.Column('max_waste_pct', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_counts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('counted_by_id', sa.String(), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counted_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_counts_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('write_off_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('deduction_type', sa.String(), nullable=False),
    sa.Column('charged_employee_id', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iiko_sync_status', sa.String(), nullable=False),
    sa.Column('iiko_external_id', sa.String(), nullable=True),
    sa.Column('iiko_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['charged_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('write_off_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_write_off_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_write_off_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_write_off_requests_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_write_off_requests_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_write_off_requests_status'), ['status'], unique=False)

    op.create_table('inventory_count_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('count_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('counted_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['inventory_counts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_count_lines')
    with op.batch_alter_table('write_off_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_write_off_requests_status'))
        batch_op.drop_index(batch_op.f('ix_write_off_requests_product_id'))
        batch_op.drop_index(batch_op.f('ix_write_off_requests_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_write_off_requests_employee_id'))
        batch_op.drop_index(batch_op.f('ix_write_off_requests_created_at'))

    op.drop_table('write_off_requests')
    with op.batch_alter_table('inventory_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_counts_outlet_id'))

    op.drop_table('inventory_counts')
    op.drop_table('waste_norms')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    op.drop_table('employees')
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_tokens_token'))

    op.drop_table('qr_tokens')
    op.drop_table('products')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_sha256_hash'))

    op.drop_table('photos')
    op.drop_table('outlets')
    with op.batch_alter_table('iiko_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iiko_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_iiko_sync_jobs_entity_id'))

    op.drop_table('iiko_sync_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
